data <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, stringsAsFactors = FALSE, na.strings = "?")
str(data)
data$datetime <- paste(data$Date, data$Time, sep=" ")
data$datetime <- strptime(data$datetime, format="%d/%m/%Y %H:%M:%S")
data$Date <- as.Date(data$Date, format = "%d/%m/%Y")
data1 <- subset(data, Date =="2007-02-01" | Date == "2007-02-02")
str(data1)

## plot4
par(mfcol = c(2, 2), mar = c(4, 4, 1, 1), oma = c(0, 0, 0, 0))
##par(mfcol = c(2, 2))
plot(data1$datetime, data1$Global_active_power, xlab="", ylab = "Global Active Power(kilowatts)", type = "l")
plot (data1$datetime, data1$Sub_metering_1, xlab ="", ylab = "Energy sub metering", type ="l")
lines (data1$datetime, data1$Sub_metering_2, col ="red")
lines (data1$datetime, data1$Sub_metering_3, col ="blue")
legend("topright", lty= c(1,1,1), lwd = c(2,2,2), col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(data1$datetime, data1$Voltage, type ="l")
plot(data1$datetime, data1$Global_reactive_power, type ="l")
dev.copy(png, file = "plot4.png") ## Copy my plot to a PNG file
dev.off()